spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        "[globally_quoted_identifiers]": true
        "[globally_quoted_identifiers_skip_column_definitions]": true
        dialect: org.hibernate.dialect.MySQL57Dialect
  session:
    store-type: jdbc
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
server:
  servlet:
    encoding:
      force: true